name: Starts testing of QGDFoam

on:
  workflow_dispatch:

jobs:
  start-VnV-QGDFoam:
    runs-on: ubuntu-latest
    steps:
     - name: Starts the process of QGDFoam verification and validation
       run: |
         curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.VNVEXECUTE }}" -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/mkraposhin/VnV/dispatches -d '{"event_type":"dispatch-event"}'
