name: Starts testing of QGDFoam

on:
  workflow_dispatch:

jobs:
  start-VnV-QGDFoam:
    runs-on: ubuntu-latest
    steps:
     - name: Starts the process of QGDFoam verification and validation
       run: |
          curl -X POST https://api.github.com/repos/mkraposhin/VnV/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.VNVEXECUTE }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
     - uses: actions/checkout@v3
